### ISSUE TITLE
Consider renaming to Cytoscape.NET

### ISSUE THREAD

**Issue by kMutagene** [fslaborg/Cytoscape.NET#11]
While I get where the name is coming from, Cyjs is not something I would google first when searching for a library that can create **Cytoscape(.js)** graphs in a .NET programming language. To make the lib more discoverable, I suggest renaming it to Cytoscape.NET - something that worked quite well for Plotly.NET as well.

**Comment by kMutagene** [comment]
Just crossed my mind that the .NET suffix here is extra cool because you can read it as an abbreviation for network 😆

**Comment by kMutagene** [comment]
cc @muehlhaus @bvenn @LibraChris @HLWeil

**Comment by muehlhaus** [comment]
In principle I like the idea. However, the reason I named it different in the first place was: Cytoscape itselve is JAVA, Cytoscape.js is a complete reimplementation in Javascript. Ergo a different name...
In the end, I don't mind changing it ...

**Comment by kMutagene** [comment]
Done, packages are now live as [Cytoscape.NET](https://www.nuget.org/packages/Cytoscape.NET/) and [Cytoscape.NET.Interactive](https://www.nuget.org/packages/Cytoscape.NET.Interactive/) on nuget.
