### ISSUE TITLE
Render in a polyglot notebook

### ISSUE THREAD

**Issue by HarryMcCarney** [fslaborg/Cytoscape.NET#9]
Is there a  way to do this or does it always need to load in a browser?

**Comment by muehlhaus** [comment]
Hi @HarryMcCarney , unfortunately we have only in browser support at the moment. I will have a look how easy this can be changed...

**Comment by GeorgeS2019** [comment]
Render to SVG, and the polyglot notebbok will display it.

**Comment by HarryMcCarney** [comment]
Thanks @muehlhaus and @GeorgeS2019. In case you were wondering this is what the pallet distribution network in Chile looks like 

<img width="1270" alt="image" src="https://user-images.githubusercontent.com/876783/226139448-cd197e5d-9a7e-4575-8c51-aa3f404c4a80.png">

**Comment by HarryMcCarney** [comment]
@GeorgeS2019 have you got an example of rendering to SVG? Unless I have missed something the lib doesn't seem to support this.

**Comment by kMutagene** [comment]
@HarryMcCarney The ground work for rendering `CyGraph`s is merged and released. There is some work to do internally (e.g. sizing does not work atm: #14 ), but there are now no technical blockers anymore. You'll just need to reference the new `Cytoscape.NET.Interactive` nuget package, and end cells with the CyGraph object:

![image](https://github.com/fslaborg/Cytoscape.NET/assets/21338071/79629d91-4e68-4757-bd59-f998014cb021)
